logging:
  level:
    ROOT: ERROR
  file: /var/log/okky/okky-config.log

server:
  port: 9000

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /okky-actuator

spring:
  cloud:
    config:
      server:
        git:
          uri: # required. 개발용에서는 local git에 설정하는 것이 좋음 ex) file:/Users/coding8282/IdeaProjects/code/okky-config-store-dev
          username:
          password: