version: 0.0
os: linux

files:
  - source: okky-config-1.0.0.jar
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: terminate-app.sh
      timeout: 30
  AfterInstall:
    - location: start-app.sh
      timeout: 30
  ValidateService:
    - location: validate-app.sh
      timeout: 120