version: 0.2

phases:
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - integration/appspec.yml
    - integration/scripts/*
    - target/okky-config-1.0.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'